###
GET http://localhost:3000/api/v1/books HTTP/1.1


###
POST http://localhost:3000/api/v1/books HTTP/1.1
Content-Type: application/json

{
  "title": "Modern Java in Action: Lambdas, streams, functional and reactive programming",
  "author": "Raoul-Gabriel Urma",
  "edition": "2nd Edition",
  "isbn": "978-1617293566",
  "publisher": "Manning",
  "pages": 592,
  "published": "11/15/2018",
  "category": "Java",
  "total_units": 10,
  "available_units": 10,
  "borrow_units":0
}

###
GET http://localhost:3000/api/v1/books/category/Non-Fiction HTTP/1.1


###
GET http://localhost:3000/api/v1/books/author/Jonathan Wexler HTTP/1.1

###
GET http://localhost:3000/api/v1/books/isbn/978-1260463552 HTTP/1.1


###
GET http://localhost:3000/api/v1/books/64821bf5ff0f708d74103f36 HTTP/1.1




###
DELETE http://localhost:3000/api/v1/books/64821b3eff0f708d74103f32 HTTP/1.1


###
GET http://localhost:3000/api/v1/users/ HTTP/1.1


###
POST http://localhost:3000/api/v1/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Touka",
  "lastname": "Kirishima",
  "email":"touka@gmail.com",
  "password":"101010"
}

###
POST http://localhost:3000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "touka@gmail.com",
  "password": "101010"
}


###
POST http://localhost:3000/api/v1/borrow/978-1617293566 HTTP/1.1
Content-Type: application/json

{
  "email": "touka@gmail.com",
  "borrow_units":2
}


