name: "My First Workflow"

on: 
  workflow_dispatch:
  
  push:
      branches:
       - main
       - feature/*
       
jobs:
 compile:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
         node-version: 18.x
      
    - name: Install
      run: |
       npm ci --silent
       npm run build
      working-directory: src
